// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

/**
 * <pre>
 * ConditionExecution is selecting multiple operations to satisfy the operation of the conditional operation
 * </pre>
 *
 * Protobuf type {@code metapb.ConditionExecution}
 */
public  final class ConditionExecution extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metapb.ConditionExecution)
    ConditionExecutionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConditionExecution.newBuilder() to construct.
  private ConditionExecution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConditionExecution() {
    nextStep_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConditionExecution(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder subBuilder = null;
            if (condition_ != null) {
              subBuilder = condition_.toBuilder();
            }
            condition_ = input.readMessage(cn.infinivision.dataforce.busybee.pb.meta.Expr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(condition_);
              condition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder subBuilder = null;
            if (execution_ != null) {
              subBuilder = execution_.toBuilder();
            }
            execution_ = input.readMessage(cn.infinivision.dataforce.busybee.pb.meta.Execution.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(execution_);
              execution_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nextStep_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_ConditionExecution_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_ConditionExecution_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.class, cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.Builder.class);
  }

  public static final int CONDITION_FIELD_NUMBER = 1;
  private cn.infinivision.dataforce.busybee.pb.meta.Expr condition_;
  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  public boolean hasCondition() {
    return condition_ != null;
  }
  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.Expr getCondition() {
    return condition_ == null ? cn.infinivision.dataforce.busybee.pb.meta.Expr.getDefaultInstance() : condition_;
  }
  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder getConditionOrBuilder() {
    return getCondition();
  }

  public static final int EXECUTION_FIELD_NUMBER = 2;
  private cn.infinivision.dataforce.busybee.pb.meta.Execution execution_;
  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  public boolean hasExecution() {
    return execution_ != null;
  }
  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.Execution getExecution() {
    return execution_ == null ? cn.infinivision.dataforce.busybee.pb.meta.Execution.getDefaultInstance() : execution_;
  }
  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder getExecutionOrBuilder() {
    return getExecution();
  }

  public static final int NEXTSTEP_FIELD_NUMBER = 3;
  private volatile java.lang.Object nextStep_;
  /**
   * <code>string nextStep = 3;</code>
   */
  public java.lang.String getNextStep() {
    java.lang.Object ref = nextStep_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextStep_ = s;
      return s;
    }
  }
  /**
   * <code>string nextStep = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNextStepBytes() {
    java.lang.Object ref = nextStep_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextStep_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (condition_ != null) {
      output.writeMessage(1, getCondition());
    }
    if (execution_ != null) {
      output.writeMessage(2, getExecution());
    }
    if (!getNextStepBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nextStep_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (condition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCondition());
    }
    if (execution_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExecution());
    }
    if (!getNextStepBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nextStep_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution)) {
      return super.equals(obj);
    }
    cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution other = (cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution) obj;

    boolean result = true;
    result = result && (hasCondition() == other.hasCondition());
    if (hasCondition()) {
      result = result && getCondition()
          .equals(other.getCondition());
    }
    result = result && (hasExecution() == other.hasExecution());
    if (hasExecution()) {
      result = result && getExecution()
          .equals(other.getExecution());
    }
    result = result && getNextStep()
        .equals(other.getNextStep());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCondition()) {
      hash = (37 * hash) + CONDITION_FIELD_NUMBER;
      hash = (53 * hash) + getCondition().hashCode();
    }
    if (hasExecution()) {
      hash = (37 * hash) + EXECUTION_FIELD_NUMBER;
      hash = (53 * hash) + getExecution().hashCode();
    }
    hash = (37 * hash) + NEXTSTEP_FIELD_NUMBER;
    hash = (53 * hash) + getNextStep().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ConditionExecution is selecting multiple operations to satisfy the operation of the conditional operation
   * </pre>
   *
   * Protobuf type {@code metapb.ConditionExecution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metapb.ConditionExecution)
      cn.infinivision.dataforce.busybee.pb.meta.ConditionExecutionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_ConditionExecution_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_ConditionExecution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.class, cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.Builder.class);
    }

    // Construct using cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (conditionBuilder_ == null) {
        condition_ = null;
      } else {
        condition_ = null;
        conditionBuilder_ = null;
      }
      if (executionBuilder_ == null) {
        execution_ = null;
      } else {
        execution_ = null;
        executionBuilder_ = null;
      }
      nextStep_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_ConditionExecution_descriptor;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution getDefaultInstanceForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.getDefaultInstance();
    }

    public cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution build() {
      cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution buildPartial() {
      cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution result = new cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution(this);
      if (conditionBuilder_ == null) {
        result.condition_ = condition_;
      } else {
        result.condition_ = conditionBuilder_.build();
      }
      if (executionBuilder_ == null) {
        result.execution_ = execution_;
      } else {
        result.execution_ = executionBuilder_.build();
      }
      result.nextStep_ = nextStep_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution) {
        return mergeFrom((cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution other) {
      if (other == cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution.getDefaultInstance()) return this;
      if (other.hasCondition()) {
        mergeCondition(other.getCondition());
      }
      if (other.hasExecution()) {
        mergeExecution(other.getExecution());
      }
      if (!other.getNextStep().isEmpty()) {
        nextStep_ = other.nextStep_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private cn.infinivision.dataforce.busybee.pb.meta.Expr condition_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.Expr, cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder> conditionBuilder_;
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public boolean hasCondition() {
      return conditionBuilder_ != null || condition_ != null;
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.Expr getCondition() {
      if (conditionBuilder_ == null) {
        return condition_ == null ? cn.infinivision.dataforce.busybee.pb.meta.Expr.getDefaultInstance() : condition_;
      } else {
        return conditionBuilder_.getMessage();
      }
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public Builder setCondition(cn.infinivision.dataforce.busybee.pb.meta.Expr value) {
      if (conditionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        condition_ = value;
        onChanged();
      } else {
        conditionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public Builder setCondition(
        cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder builderForValue) {
      if (conditionBuilder_ == null) {
        condition_ = builderForValue.build();
        onChanged();
      } else {
        conditionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public Builder mergeCondition(cn.infinivision.dataforce.busybee.pb.meta.Expr value) {
      if (conditionBuilder_ == null) {
        if (condition_ != null) {
          condition_ =
            cn.infinivision.dataforce.busybee.pb.meta.Expr.newBuilder(condition_).mergeFrom(value).buildPartial();
        } else {
          condition_ = value;
        }
        onChanged();
      } else {
        conditionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public Builder clearCondition() {
      if (conditionBuilder_ == null) {
        condition_ = null;
        onChanged();
      } else {
        condition_ = null;
        conditionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder getConditionBuilder() {
      
      onChanged();
      return getConditionFieldBuilder().getBuilder();
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder getConditionOrBuilder() {
      if (conditionBuilder_ != null) {
        return conditionBuilder_.getMessageOrBuilder();
      } else {
        return condition_ == null ?
            cn.infinivision.dataforce.busybee.pb.meta.Expr.getDefaultInstance() : condition_;
      }
    }
    /**
     * <code>.metapb.Expr condition = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.Expr, cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder> 
        getConditionFieldBuilder() {
      if (conditionBuilder_ == null) {
        conditionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.infinivision.dataforce.busybee.pb.meta.Expr, cn.infinivision.dataforce.busybee.pb.meta.Expr.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder>(
                getCondition(),
                getParentForChildren(),
                isClean());
        condition_ = null;
      }
      return conditionBuilder_;
    }

    private cn.infinivision.dataforce.busybee.pb.meta.Execution execution_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.Execution, cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder> executionBuilder_;
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public boolean hasExecution() {
      return executionBuilder_ != null || execution_ != null;
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.Execution getExecution() {
      if (executionBuilder_ == null) {
        return execution_ == null ? cn.infinivision.dataforce.busybee.pb.meta.Execution.getDefaultInstance() : execution_;
      } else {
        return executionBuilder_.getMessage();
      }
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public Builder setExecution(cn.infinivision.dataforce.busybee.pb.meta.Execution value) {
      if (executionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        execution_ = value;
        onChanged();
      } else {
        executionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public Builder setExecution(
        cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder builderForValue) {
      if (executionBuilder_ == null) {
        execution_ = builderForValue.build();
        onChanged();
      } else {
        executionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public Builder mergeExecution(cn.infinivision.dataforce.busybee.pb.meta.Execution value) {
      if (executionBuilder_ == null) {
        if (execution_ != null) {
          execution_ =
            cn.infinivision.dataforce.busybee.pb.meta.Execution.newBuilder(execution_).mergeFrom(value).buildPartial();
        } else {
          execution_ = value;
        }
        onChanged();
      } else {
        executionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public Builder clearExecution() {
      if (executionBuilder_ == null) {
        execution_ = null;
        onChanged();
      } else {
        execution_ = null;
        executionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder getExecutionBuilder() {
      
      onChanged();
      return getExecutionFieldBuilder().getBuilder();
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder getExecutionOrBuilder() {
      if (executionBuilder_ != null) {
        return executionBuilder_.getMessageOrBuilder();
      } else {
        return execution_ == null ?
            cn.infinivision.dataforce.busybee.pb.meta.Execution.getDefaultInstance() : execution_;
      }
    }
    /**
     * <code>.metapb.Execution execution = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.Execution, cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder> 
        getExecutionFieldBuilder() {
      if (executionBuilder_ == null) {
        executionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.infinivision.dataforce.busybee.pb.meta.Execution, cn.infinivision.dataforce.busybee.pb.meta.Execution.Builder, cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder>(
                getExecution(),
                getParentForChildren(),
                isClean());
        execution_ = null;
      }
      return executionBuilder_;
    }

    private java.lang.Object nextStep_ = "";
    /**
     * <code>string nextStep = 3;</code>
     */
    public java.lang.String getNextStep() {
      java.lang.Object ref = nextStep_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextStep_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nextStep = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNextStepBytes() {
      java.lang.Object ref = nextStep_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextStep_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nextStep = 3;</code>
     */
    public Builder setNextStep(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextStep_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nextStep = 3;</code>
     */
    public Builder clearNextStep() {
      
      nextStep_ = getDefaultInstance().getNextStep();
      onChanged();
      return this;
    }
    /**
     * <code>string nextStep = 3;</code>
     */
    public Builder setNextStepBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextStep_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metapb.ConditionExecution)
  }

  // @@protoc_insertion_point(class_scope:metapb.ConditionExecution)
  private static final cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution();
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConditionExecution>
      PARSER = new com.google.protobuf.AbstractParser<ConditionExecution>() {
    public ConditionExecution parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConditionExecution(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConditionExecution> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConditionExecution> getParserForType() {
    return PARSER;
  }

  public cn.infinivision.dataforce.busybee.pb.meta.ConditionExecution getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

