// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

/**
 * <pre>
 * Event tenant event
 * </pre>
 *
 * Protobuf type {@code metapb.Event}
 */
public  final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metapb.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    type_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(cn.infinivision.dataforce.busybee.pb.meta.UserEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder subBuilder = null;
            if (updateCrowd_ != null) {
              subBuilder = updateCrowd_.toBuilder();
            }
            updateCrowd_ = input.readMessage(cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updateCrowd_);
              updateCrowd_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder subBuilder = null;
            if (updateWorkflow_ != null) {
              subBuilder = updateWorkflow_.toBuilder();
            }
            updateWorkflow_ = input.readMessage(cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updateWorkflow_);
              updateWorkflow_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_Event_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.infinivision.dataforce.busybee.pb.meta.Event.class, cn.infinivision.dataforce.busybee.pb.meta.Event.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.metapb.EventType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.metapb.EventType type = 1;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.EventType getType() {
    cn.infinivision.dataforce.busybee.pb.meta.EventType result = cn.infinivision.dataforce.busybee.pb.meta.EventType.valueOf(type_);
    return result == null ? cn.infinivision.dataforce.busybee.pb.meta.EventType.UNRECOGNIZED : result;
  }

  public static final int USER_FIELD_NUMBER = 2;
  private cn.infinivision.dataforce.busybee.pb.meta.UserEvent user_;
  /**
   * <code>.metapb.UserEvent user = 2;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.metapb.UserEvent user = 2;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UserEvent getUser() {
    return user_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UserEvent.getDefaultInstance() : user_;
  }
  /**
   * <code>.metapb.UserEvent user = 2;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UserEventOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int UPDATECROWD_FIELD_NUMBER = 3;
  private cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent updateCrowd_;
  /**
   * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
   */
  public boolean hasUpdateCrowd() {
    return updateCrowd_ != null;
  }
  /**
   * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent getUpdateCrowd() {
    return updateCrowd_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.getDefaultInstance() : updateCrowd_;
  }
  /**
   * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEventOrBuilder getUpdateCrowdOrBuilder() {
    return getUpdateCrowd();
  }

  public static final int UPDATEWORKFLOW_FIELD_NUMBER = 4;
  private cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent updateWorkflow_;
  /**
   * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
   */
  public boolean hasUpdateWorkflow() {
    return updateWorkflow_ != null;
  }
  /**
   * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent getUpdateWorkflow() {
    return updateWorkflow_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.getDefaultInstance() : updateWorkflow_;
  }
  /**
   * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
   */
  public cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEventOrBuilder getUpdateWorkflowOrBuilder() {
    return getUpdateWorkflow();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != cn.infinivision.dataforce.busybee.pb.meta.EventType.UserType.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (user_ != null) {
      output.writeMessage(2, getUser());
    }
    if (updateCrowd_ != null) {
      output.writeMessage(3, getUpdateCrowd());
    }
    if (updateWorkflow_ != null) {
      output.writeMessage(4, getUpdateWorkflow());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != cn.infinivision.dataforce.busybee.pb.meta.EventType.UserType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    if (updateCrowd_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUpdateCrowd());
    }
    if (updateWorkflow_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUpdateWorkflow());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.infinivision.dataforce.busybee.pb.meta.Event)) {
      return super.equals(obj);
    }
    cn.infinivision.dataforce.busybee.pb.meta.Event other = (cn.infinivision.dataforce.busybee.pb.meta.Event) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && (hasUpdateCrowd() == other.hasUpdateCrowd());
    if (hasUpdateCrowd()) {
      result = result && getUpdateCrowd()
          .equals(other.getUpdateCrowd());
    }
    result = result && (hasUpdateWorkflow() == other.hasUpdateWorkflow());
    if (hasUpdateWorkflow()) {
      result = result && getUpdateWorkflow()
          .equals(other.getUpdateWorkflow());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasUpdateCrowd()) {
      hash = (37 * hash) + UPDATECROWD_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateCrowd().hashCode();
    }
    if (hasUpdateWorkflow()) {
      hash = (37 * hash) + UPDATEWORKFLOW_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateWorkflow().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.infinivision.dataforce.busybee.pb.meta.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Event tenant event
   * </pre>
   *
   * Protobuf type {@code metapb.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metapb.Event)
      cn.infinivision.dataforce.busybee.pb.meta.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.infinivision.dataforce.busybee.pb.meta.Event.class, cn.infinivision.dataforce.busybee.pb.meta.Event.Builder.class);
    }

    // Construct using cn.infinivision.dataforce.busybee.pb.meta.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (updateCrowdBuilder_ == null) {
        updateCrowd_ = null;
      } else {
        updateCrowd_ = null;
        updateCrowdBuilder_ = null;
      }
      if (updateWorkflowBuilder_ == null) {
        updateWorkflow_ = null;
      } else {
        updateWorkflow_ = null;
        updateWorkflowBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_Event_descriptor;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.Event getDefaultInstanceForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.Event.getDefaultInstance();
    }

    public cn.infinivision.dataforce.busybee.pb.meta.Event build() {
      cn.infinivision.dataforce.busybee.pb.meta.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.Event buildPartial() {
      cn.infinivision.dataforce.busybee.pb.meta.Event result = new cn.infinivision.dataforce.busybee.pb.meta.Event(this);
      result.type_ = type_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (updateCrowdBuilder_ == null) {
        result.updateCrowd_ = updateCrowd_;
      } else {
        result.updateCrowd_ = updateCrowdBuilder_.build();
      }
      if (updateWorkflowBuilder_ == null) {
        result.updateWorkflow_ = updateWorkflow_;
      } else {
        result.updateWorkflow_ = updateWorkflowBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.infinivision.dataforce.busybee.pb.meta.Event) {
        return mergeFrom((cn.infinivision.dataforce.busybee.pb.meta.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.infinivision.dataforce.busybee.pb.meta.Event other) {
      if (other == cn.infinivision.dataforce.busybee.pb.meta.Event.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasUpdateCrowd()) {
        mergeUpdateCrowd(other.getUpdateCrowd());
      }
      if (other.hasUpdateWorkflow()) {
        mergeUpdateWorkflow(other.getUpdateWorkflow());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.infinivision.dataforce.busybee.pb.meta.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.infinivision.dataforce.busybee.pb.meta.Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.metapb.EventType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.metapb.EventType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.metapb.EventType type = 1;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.EventType getType() {
      cn.infinivision.dataforce.busybee.pb.meta.EventType result = cn.infinivision.dataforce.busybee.pb.meta.EventType.valueOf(type_);
      return result == null ? cn.infinivision.dataforce.busybee.pb.meta.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.metapb.EventType type = 1;</code>
     */
    public Builder setType(cn.infinivision.dataforce.busybee.pb.meta.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.metapb.EventType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private cn.infinivision.dataforce.busybee.pb.meta.UserEvent user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UserEvent, cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UserEventOrBuilder> userBuilder_;
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UserEvent getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UserEvent.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public Builder setUser(cn.infinivision.dataforce.busybee.pb.meta.UserEvent value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public Builder setUser(
        cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public Builder mergeUser(cn.infinivision.dataforce.busybee.pb.meta.UserEvent value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            cn.infinivision.dataforce.busybee.pb.meta.UserEvent.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UserEventOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            cn.infinivision.dataforce.busybee.pb.meta.UserEvent.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.metapb.UserEvent user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UserEvent, cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UserEventOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.infinivision.dataforce.busybee.pb.meta.UserEvent, cn.infinivision.dataforce.busybee.pb.meta.UserEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UserEventOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent updateCrowd_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEventOrBuilder> updateCrowdBuilder_;
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public boolean hasUpdateCrowd() {
      return updateCrowdBuilder_ != null || updateCrowd_ != null;
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent getUpdateCrowd() {
      if (updateCrowdBuilder_ == null) {
        return updateCrowd_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.getDefaultInstance() : updateCrowd_;
      } else {
        return updateCrowdBuilder_.getMessage();
      }
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public Builder setUpdateCrowd(cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent value) {
      if (updateCrowdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateCrowd_ = value;
        onChanged();
      } else {
        updateCrowdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public Builder setUpdateCrowd(
        cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder builderForValue) {
      if (updateCrowdBuilder_ == null) {
        updateCrowd_ = builderForValue.build();
        onChanged();
      } else {
        updateCrowdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public Builder mergeUpdateCrowd(cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent value) {
      if (updateCrowdBuilder_ == null) {
        if (updateCrowd_ != null) {
          updateCrowd_ =
            cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.newBuilder(updateCrowd_).mergeFrom(value).buildPartial();
        } else {
          updateCrowd_ = value;
        }
        onChanged();
      } else {
        updateCrowdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public Builder clearUpdateCrowd() {
      if (updateCrowdBuilder_ == null) {
        updateCrowd_ = null;
        onChanged();
      } else {
        updateCrowd_ = null;
        updateCrowdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder getUpdateCrowdBuilder() {
      
      onChanged();
      return getUpdateCrowdFieldBuilder().getBuilder();
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEventOrBuilder getUpdateCrowdOrBuilder() {
      if (updateCrowdBuilder_ != null) {
        return updateCrowdBuilder_.getMessageOrBuilder();
      } else {
        return updateCrowd_ == null ?
            cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.getDefaultInstance() : updateCrowd_;
      }
    }
    /**
     * <code>.metapb.UpdateCrowdEvent updateCrowd = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEventOrBuilder> 
        getUpdateCrowdFieldBuilder() {
      if (updateCrowdBuilder_ == null) {
        updateCrowdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateCrowdEventOrBuilder>(
                getUpdateCrowd(),
                getParentForChildren(),
                isClean());
        updateCrowd_ = null;
      }
      return updateCrowdBuilder_;
    }

    private cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent updateWorkflow_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEventOrBuilder> updateWorkflowBuilder_;
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public boolean hasUpdateWorkflow() {
      return updateWorkflowBuilder_ != null || updateWorkflow_ != null;
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent getUpdateWorkflow() {
      if (updateWorkflowBuilder_ == null) {
        return updateWorkflow_ == null ? cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.getDefaultInstance() : updateWorkflow_;
      } else {
        return updateWorkflowBuilder_.getMessage();
      }
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public Builder setUpdateWorkflow(cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent value) {
      if (updateWorkflowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateWorkflow_ = value;
        onChanged();
      } else {
        updateWorkflowBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public Builder setUpdateWorkflow(
        cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder builderForValue) {
      if (updateWorkflowBuilder_ == null) {
        updateWorkflow_ = builderForValue.build();
        onChanged();
      } else {
        updateWorkflowBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public Builder mergeUpdateWorkflow(cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent value) {
      if (updateWorkflowBuilder_ == null) {
        if (updateWorkflow_ != null) {
          updateWorkflow_ =
            cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.newBuilder(updateWorkflow_).mergeFrom(value).buildPartial();
        } else {
          updateWorkflow_ = value;
        }
        onChanged();
      } else {
        updateWorkflowBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public Builder clearUpdateWorkflow() {
      if (updateWorkflowBuilder_ == null) {
        updateWorkflow_ = null;
        onChanged();
      } else {
        updateWorkflow_ = null;
        updateWorkflowBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder getUpdateWorkflowBuilder() {
      
      onChanged();
      return getUpdateWorkflowFieldBuilder().getBuilder();
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    public cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEventOrBuilder getUpdateWorkflowOrBuilder() {
      if (updateWorkflowBuilder_ != null) {
        return updateWorkflowBuilder_.getMessageOrBuilder();
      } else {
        return updateWorkflow_ == null ?
            cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.getDefaultInstance() : updateWorkflow_;
      }
    }
    /**
     * <code>.metapb.UpdateWorkflowEvent updateWorkflow = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEventOrBuilder> 
        getUpdateWorkflowFieldBuilder() {
      if (updateWorkflowBuilder_ == null) {
        updateWorkflowBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEvent.Builder, cn.infinivision.dataforce.busybee.pb.meta.UpdateWorkflowEventOrBuilder>(
                getUpdateWorkflow(),
                getParentForChildren(),
                isClean());
        updateWorkflow_ = null;
      }
      return updateWorkflowBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metapb.Event)
  }

  // @@protoc_insertion_point(class_scope:metapb.Event)
  private static final cn.infinivision.dataforce.busybee.pb.meta.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.infinivision.dataforce.busybee.pb.meta.Event();
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  public cn.infinivision.dataforce.busybee.pb.meta.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

