// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public final class PB {
  private PB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_ShardBitmapPutMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_ShardBitmapPutMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_ShardBitmapLoadMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_ShardBitmapLoadMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_UpdateCrowdEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_UpdateCrowdEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_UpdateWorkflowEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_UpdateWorkflowEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_UserEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_UserEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_KV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_KV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Notify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Notify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_IDValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_IDValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_IDSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_IDSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Workflow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Workflow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_WorkflowInstance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_WorkflowInstance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_WorkflowInstanceSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_WorkflowInstanceSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_WorkflowInstanceWorkerState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_WorkflowInstanceWorkerState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_CountState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_CountState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_InstanceCountState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_InstanceCountState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_StepState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_StepState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Step_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Step_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Execution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Execution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_TimerExecution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_TimerExecution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_ParallelExecution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_ParallelExecution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_DirectExecution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_DirectExecution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_ConditionExecution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_ConditionExecution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metapb_Expr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metapb_Expr_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmeta.proto\022\006metapb\"E\n\022ShardBitmapPutMe" +
      "ta\022\013\n\003key\030\001 \001(\014\022\013\n\003ttl\030\002 \001(\r\022\025\n\rbytesPer" +
      "Shard\030\003 \001(\r\"A\n\023ShardBitmapLoadMeta\022\013\n\003ke" +
      "y\030\001 \001(\014\022\r\n\005Total\030\002 \001(\004\022\016\n\006shards\030\003 \001(\r\"\255" +
      "\001\n\005Event\022\037\n\004type\030\001 \001(\0162\021.metapb.EventTyp" +
      "e\022\037\n\004user\030\002 \001(\0132\021.metapb.UserEvent\022-\n\013up" +
      "dateCrowd\030\003 \001(\0132\030.metapb.UpdateCrowdEven" +
      "t\0223\n\016updateWorkflow\030\004 \001(\0132\033.metapb.Updat" +
      "eWorkflowEvent\"D\n\020UpdateCrowdEvent\022\022\n\nwo" +
      "rkflowID\030\001 \001(\004\022\r\n\005index\030\002 \001(\r\022\r\n\005crowd\030\003" +
      " \001(\014\"9\n\023UpdateWorkflowEvent\022\"\n\010workflow\030" +
      "\001 \001(\0132\020.metapb.Workflow\"[\n\tUserEvent\022\016\n\006" +
      "userID\030\001 \001(\004\022\020\n\010tenantID\030\002 \001(\004\022\022\n\nworkfl" +
      "owID\030\003 \001(\004\022\030\n\004data\030\004 \003(\0132\n.metapb.KV\" \n\002" +
      "KV\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\"\242\001\n\006Notif" +
      "y\022\016\n\006userID\030\001 \001(\r\022\r\n\005crowd\030\002 \001(\014\022\020\n\010tena" +
      "ntID\030\003 \001(\004\022\022\n\nworkflowID\030\004 \001(\004\022\020\n\010fromSt" +
      "ep\030\005 \001(\t\022\022\n\nfromAction\030\006 \001(\t\022\016\n\006toStep\030\007" +
      " \001(\t\022\020\n\010toAction\030\010 \001(\t\022\013\n\003ttl\030\t \001(\005\"&\n\007I" +
      "DValue\022\r\n\005value\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\"(\n\005I" +
      "DSet\022\037\n\006values\030\001 \003(\0132\017.metapb.IDValue\"e\n" +
      "\010Workflow\022\n\n\002id\030\001 \001(\004\022\020\n\010tenantID\030\002 \001(\004\022" +
      "\014\n\004name\030\003 \001(\t\022\033\n\005steps\030\004 \003(\0132\014.metapb.St" +
      "ep\022\020\n\010duration\030\005 \001(\003\"\212\002\n\020WorkflowInstanc" +
      "e\022\"\n\010snapshot\030\001 \001(\0132\020.metapb.Workflow\022\022\n" +
      "\ninstanceID\030\002 \001(\004\022\022\n\nloaderMeta\030\003 \001(\014\022 \n" +
      "\006loader\030\004 \001(\0162\020.metapb.BMLoader\022\022\n\ntotal" +
      "Crowd\030\005 \001(\004\022\017\n\007workers\030\006 \001(\004\022\021\n\tstartedA" +
      "t\030\007 \001(\003\022\021\n\tstoppedAt\030\010 \001(\003\022\017\n\007version\030\t " +
      "\001(\004\022,\n\005state\030\n \001(\0162\035.metapb.WorkflowInst" +
      "anceState\"|\n\030WorkflowInstanceSnapshot\022*\n" +
      "\010snapshot\030\001 \001(\0132\030.metapb.WorkflowInstanc" +
      "e\022\021\n\ttimestamp\030\002 \001(\003\022!\n\006states\030\003 \003(\0132\021.m" +
      "etapb.StepState\"\226\001\n\033WorkflowInstanceWork" +
      "erState\022\020\n\010tenantID\030\001 \001(\004\022\022\n\nworkflowID\030" +
      "\002 \001(\004\022\r\n\005index\030\003 \001(\r\022!\n\006states\030\004 \003(\0132\021.m" +
      "etapb.StepState\022\017\n\007version\030\005 \001(\004\022\016\n\006stop" +
      "At\030\006 \001(\003\")\n\nCountState\022\014\n\004step\030\001 \001(\t\022\r\n\005" +
      "count\030\002 \001(\004\"k\n\022InstanceCountState\022\"\n\010sna" +
      "pshot\030\001 \001(\0132\020.metapb.Workflow\022\"\n\006states\030" +
      "\002 \003(\0132\022.metapb.CountState\022\r\n\005total\030\003 \001(\004" +
      "\"q\n\tStepState\022\032\n\004step\030\001 \001(\0132\014.metapb.Ste" +
      "p\022\022\n\ntotalCrowd\030\002 \001(\004\022 \n\006loader\030\003 \001(\0162\020." +
      "metapb.BMLoader\022\022\n\nloaderMeta\030\004 \001(\014\"q\n\004S" +
      "tep\022\014\n\004name\030\001 \001(\t\022$\n\texecution\030\002 \001(\0132\021.m" +
      "etapb.Execution\022\023\n\013enterAction\030\003 \001(\t\022\023\n\013" +
      "leaveAction\030\004 \001(\t\022\013\n\003ttl\030\005 \001(\005\"\333\001\n\tExecu" +
      "tion\022#\n\004type\030\001 \001(\0162\025.metapb.ExectuionTyp" +
      "e\022%\n\005timer\030\002 \001(\0132\026.metapb.TimerExecution" +
      "\022\'\n\006direct\030\003 \001(\0132\027.metapb.DirectExecutio" +
      "n\022,\n\010branches\030\004 \003(\0132\032.metapb.ConditionEx" +
      "ecution\022+\n\010parallel\030\005 \001(\0132\031.metapb.Paral" +
      "lelExecution\"Q\n\016TimerExecution\022\037\n\tcondit" +
      "ion\030\001 \001(\0132\014.metapb.Expr\022\014\n\004cron\030\002 \001(\t\022\020\n" +
      "\010nextStep\030\003 \001(\t\"K\n\021ParallelExecution\022\020\n\010" +
      "nextStep\030\001 \001(\t\022$\n\tparallels\030\002 \003(\0132\021.meta" +
      "pb.Execution\"#\n\017DirectExecution\022\020\n\010nextS" +
      "tep\030\001 \001(\t\"m\n\022ConditionExecution\022\037\n\tcondi" +
      "tion\030\001 \001(\0132\014.metapb.Expr\022$\n\texecution\030\002 " +
      "\001(\0132\021.metapb.Execution\022\020\n\010nextStep\030\003 \001(\t" +
      "\";\n\004Expr\022\r\n\005value\030\001 \001(\014\022$\n\004type\030\002 \001(\0162\026." +
      "metapb.ExprResultType*P\n\010BMLoader\022\r\n\tRaw" +
      "Loader\020\000\022\014\n\010KVLoader\020\001\022\021\n\rKVShardLoader\020" +
      "\002\022\024\n\020ClickhouseLoader\020\003*M\n\025WorkflowInsta" +
      "nceState\022\014\n\010Starting\020\000\022\013\n\007Running\020\001\022\014\n\010S" +
      "topping\020\002\022\013\n\007Stopped\020\003*F\n\tEventType\022\014\n\010U" +
      "serType\020\000\022\023\n\017UpdateCrowdType\020\001\022\026\n\022Update" +
      "WorkflowType\020\002*F\n\005Group\022\020\n\014DefaultGroup\020" +
      "\000\022\024\n\020TenantInputGroup\020\001\022\025\n\021TenantOutputG" +
      "roup\020\002*@\n\rExectuionType\022\n\n\006Direct\020\000\022\t\n\005T" +
      "imer\020\001\022\n\n\006Branch\020\002\022\014\n\010Parallel\020\003*.\n\016Expr" +
      "ResultType\022\016\n\nBoolResult\020\000\022\014\n\010BMResult\020\001" +
      "B7\n)cn.infinivision.dataforce.busybee.pb" +
      ".metaB\002PBP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_metapb_ShardBitmapPutMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metapb_ShardBitmapPutMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_ShardBitmapPutMeta_descriptor,
        new java.lang.String[] { "Key", "Ttl", "BytesPerShard", });
    internal_static_metapb_ShardBitmapLoadMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_metapb_ShardBitmapLoadMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_ShardBitmapLoadMeta_descriptor,
        new java.lang.String[] { "Key", "Total", "Shards", });
    internal_static_metapb_Event_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_metapb_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Event_descriptor,
        new java.lang.String[] { "Type", "User", "UpdateCrowd", "UpdateWorkflow", });
    internal_static_metapb_UpdateCrowdEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_metapb_UpdateCrowdEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_UpdateCrowdEvent_descriptor,
        new java.lang.String[] { "WorkflowID", "Index", "Crowd", });
    internal_static_metapb_UpdateWorkflowEvent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_metapb_UpdateWorkflowEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_UpdateWorkflowEvent_descriptor,
        new java.lang.String[] { "Workflow", });
    internal_static_metapb_UserEvent_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_metapb_UserEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_UserEvent_descriptor,
        new java.lang.String[] { "UserID", "TenantID", "WorkflowID", "Data", });
    internal_static_metapb_KV_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_metapb_KV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_KV_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_metapb_Notify_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_metapb_Notify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Notify_descriptor,
        new java.lang.String[] { "UserID", "Crowd", "TenantID", "WorkflowID", "FromStep", "FromAction", "ToStep", "ToAction", "Ttl", });
    internal_static_metapb_IDValue_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_metapb_IDValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_IDValue_descriptor,
        new java.lang.String[] { "Value", "Type", });
    internal_static_metapb_IDSet_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_metapb_IDSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_IDSet_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_metapb_Workflow_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_metapb_Workflow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Workflow_descriptor,
        new java.lang.String[] { "Id", "TenantID", "Name", "Steps", "Duration", });
    internal_static_metapb_WorkflowInstance_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_metapb_WorkflowInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_WorkflowInstance_descriptor,
        new java.lang.String[] { "Snapshot", "InstanceID", "LoaderMeta", "Loader", "TotalCrowd", "Workers", "StartedAt", "StoppedAt", "Version", "State", });
    internal_static_metapb_WorkflowInstanceSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_metapb_WorkflowInstanceSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_WorkflowInstanceSnapshot_descriptor,
        new java.lang.String[] { "Snapshot", "Timestamp", "States", });
    internal_static_metapb_WorkflowInstanceWorkerState_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_metapb_WorkflowInstanceWorkerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_WorkflowInstanceWorkerState_descriptor,
        new java.lang.String[] { "TenantID", "WorkflowID", "Index", "States", "Version", "StopAt", });
    internal_static_metapb_CountState_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_metapb_CountState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_CountState_descriptor,
        new java.lang.String[] { "Step", "Count", });
    internal_static_metapb_InstanceCountState_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_metapb_InstanceCountState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_InstanceCountState_descriptor,
        new java.lang.String[] { "Snapshot", "States", "Total", });
    internal_static_metapb_StepState_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_metapb_StepState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_StepState_descriptor,
        new java.lang.String[] { "Step", "TotalCrowd", "Loader", "LoaderMeta", });
    internal_static_metapb_Step_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_metapb_Step_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Step_descriptor,
        new java.lang.String[] { "Name", "Execution", "EnterAction", "LeaveAction", "Ttl", });
    internal_static_metapb_Execution_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_metapb_Execution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Execution_descriptor,
        new java.lang.String[] { "Type", "Timer", "Direct", "Branches", "Parallel", });
    internal_static_metapb_TimerExecution_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_metapb_TimerExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_TimerExecution_descriptor,
        new java.lang.String[] { "Condition", "Cron", "NextStep", });
    internal_static_metapb_ParallelExecution_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_metapb_ParallelExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_ParallelExecution_descriptor,
        new java.lang.String[] { "NextStep", "Parallels", });
    internal_static_metapb_DirectExecution_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_metapb_DirectExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_DirectExecution_descriptor,
        new java.lang.String[] { "NextStep", });
    internal_static_metapb_ConditionExecution_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_metapb_ConditionExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_ConditionExecution_descriptor,
        new java.lang.String[] { "Condition", "Execution", "NextStep", });
    internal_static_metapb_Expr_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_metapb_Expr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metapb_Expr_descriptor,
        new java.lang.String[] { "Value", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
