// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface StepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.Step)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  boolean hasExecution();
  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.Execution getExecution();
  /**
   * <code>.metapb.Execution execution = 2;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.ExecutionOrBuilder getExecutionOrBuilder();

  /**
   * <code>string enterAction = 3;</code>
   */
  java.lang.String getEnterAction();
  /**
   * <code>string enterAction = 3;</code>
   */
  com.google.protobuf.ByteString
      getEnterActionBytes();

  /**
   * <code>string leaveAction = 4;</code>
   */
  java.lang.String getLeaveAction();
  /**
   * <code>string leaveAction = 4;</code>
   */
  com.google.protobuf.ByteString
      getLeaveActionBytes();
}
