// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface TenantQueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.TenantQueue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 partitions = 1;</code>
   */
  int getPartitions();

  /**
   * <code>int64 consumerTimeout = 2;</code>
   */
  long getConsumerTimeout();

  /**
   * <code>int64 maxAlive = 3;</code>
   */
  long getMaxAlive();

  /**
   * <code>uint64 cleanBatch = 4;</code>
   */
  long getCleanBatch();
}
