// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface TenantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.Tenant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>.metapb.TenantQueue output = 2;</code>
   */
  boolean hasOutput();
  /**
   * <code>.metapb.TenantQueue output = 2;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.TenantQueue getOutput();
  /**
   * <code>.metapb.TenantQueue output = 2;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.TenantQueueOrBuilder getOutputOrBuilder();
}
