// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface TimerExecutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.TimerExecution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  boolean hasCondition();
  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.Expr getCondition();
  /**
   * <code>.metapb.Expr condition = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.ExprOrBuilder getConditionOrBuilder();

  /**
   * <code>string cron = 2;</code>
   */
  java.lang.String getCron();
  /**
   * <code>string cron = 2;</code>
   */
  com.google.protobuf.ByteString
      getCronBytes();

  /**
   * <code>string nextStep = 3;</code>
   */
  java.lang.String getNextStep();
  /**
   * <code>string nextStep = 3;</code>
   */
  com.google.protobuf.ByteString
      getNextStepBytes();

  /**
   * <code>bool useStepCrowdToDrive = 4;</code>
   */
  boolean getUseStepCrowdToDrive();
}
