// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface UpdateCrowdEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.UpdateCrowdEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 workflowID = 1;</code>
   */
  long getWorkflowID();

  /**
   * <code>uint32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>bytes crowd = 3;</code>
   */
  com.google.protobuf.ByteString getCrowd();
}
