// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface UserEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.UserEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userID = 1;</code>
   */
  long getUserID();

  /**
   * <code>uint64 tenantID = 2;</code>
   */
  long getTenantID();

  /**
   * <code>uint64 workflowID = 3;</code>
   */
  long getWorkflowID();

  /**
   * <code>uint64 instanceID = 4;</code>
   */
  long getInstanceID();

  /**
   * <code>repeated .metapb.KV data = 5;</code>
   */
  java.util.List<cn.infinivision.dataforce.busybee.pb.meta.KV> 
      getDataList();
  /**
   * <code>repeated .metapb.KV data = 5;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.KV getData(int index);
  /**
   * <code>repeated .metapb.KV data = 5;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .metapb.KV data = 5;</code>
   */
  java.util.List<? extends cn.infinivision.dataforce.busybee.pb.meta.KVOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .metapb.KV data = 5;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.KVOrBuilder getDataOrBuilder(
      int index);
}
