// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

public interface WorkflowInstanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metapb.WorkflowInstance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.metapb.Workflow snapshot = 1;</code>
   */
  boolean hasSnapshot();
  /**
   * <code>.metapb.Workflow snapshot = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.Workflow getSnapshot();
  /**
   * <code>.metapb.Workflow snapshot = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.WorkflowOrBuilder getSnapshotOrBuilder();

  /**
   * <code>bytes crowd = 2;</code>
   */
  com.google.protobuf.ByteString getCrowd();

  /**
   * <code>uint64 workers = 3;</code>
   */
  long getWorkers();

  /**
   * <code>int64 startedAt = 4;</code>
   */
  long getStartedAt();

  /**
   * <code>int64 stoppedAt = 5;</code>
   */
  long getStoppedAt();
}
