// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

/**
 * Protobuf type {@code metapb.WorkflowWorker}
 */
public  final class WorkflowWorker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metapb.WorkflowWorker)
    WorkflowWorkerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkflowWorker.newBuilder() to construct.
  private WorkflowWorker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkflowWorker() {
    workflowID_ = 0L;
    instanceID_ = 0L;
    index_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkflowWorker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            workflowID_ = input.readUInt64();
            break;
          }
          case 16: {

            instanceID_ = input.readUInt64();
            break;
          }
          case 24: {

            index_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_WorkflowWorker_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_WorkflowWorker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.class, cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.Builder.class);
  }

  public static final int WORKFLOWID_FIELD_NUMBER = 1;
  private long workflowID_;
  /**
   * <code>uint64 workflowID = 1;</code>
   */
  public long getWorkflowID() {
    return workflowID_;
  }

  public static final int INSTANCEID_FIELD_NUMBER = 2;
  private long instanceID_;
  /**
   * <code>uint64 instanceID = 2;</code>
   */
  public long getInstanceID() {
    return instanceID_;
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private int index_;
  /**
   * <code>uint32 index = 3;</code>
   */
  public int getIndex() {
    return index_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (workflowID_ != 0L) {
      output.writeUInt64(1, workflowID_);
    }
    if (instanceID_ != 0L) {
      output.writeUInt64(2, instanceID_);
    }
    if (index_ != 0) {
      output.writeUInt32(3, index_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (workflowID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, workflowID_);
    }
    if (instanceID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, instanceID_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, index_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker)) {
      return super.equals(obj);
    }
    cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker other = (cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker) obj;

    boolean result = true;
    result = result && (getWorkflowID()
        == other.getWorkflowID());
    result = result && (getInstanceID()
        == other.getInstanceID());
    result = result && (getIndex()
        == other.getIndex());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKFLOWID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkflowID());
    hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInstanceID());
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code metapb.WorkflowWorker}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metapb.WorkflowWorker)
      cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorkerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_WorkflowWorker_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_WorkflowWorker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.class, cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.Builder.class);
    }

    // Construct using cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      workflowID_ = 0L;

      instanceID_ = 0L;

      index_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.PB.internal_static_metapb_WorkflowWorker_descriptor;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker getDefaultInstanceForType() {
      return cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.getDefaultInstance();
    }

    public cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker build() {
      cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker buildPartial() {
      cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker result = new cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker(this);
      result.workflowID_ = workflowID_;
      result.instanceID_ = instanceID_;
      result.index_ = index_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker) {
        return mergeFrom((cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker other) {
      if (other == cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker.getDefaultInstance()) return this;
      if (other.getWorkflowID() != 0L) {
        setWorkflowID(other.getWorkflowID());
      }
      if (other.getInstanceID() != 0L) {
        setInstanceID(other.getInstanceID());
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long workflowID_ ;
    /**
     * <code>uint64 workflowID = 1;</code>
     */
    public long getWorkflowID() {
      return workflowID_;
    }
    /**
     * <code>uint64 workflowID = 1;</code>
     */
    public Builder setWorkflowID(long value) {
      
      workflowID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 workflowID = 1;</code>
     */
    public Builder clearWorkflowID() {
      
      workflowID_ = 0L;
      onChanged();
      return this;
    }

    private long instanceID_ ;
    /**
     * <code>uint64 instanceID = 2;</code>
     */
    public long getInstanceID() {
      return instanceID_;
    }
    /**
     * <code>uint64 instanceID = 2;</code>
     */
    public Builder setInstanceID(long value) {
      
      instanceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 instanceID = 2;</code>
     */
    public Builder clearInstanceID() {
      
      instanceID_ = 0L;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <code>uint32 index = 3;</code>
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 index = 3;</code>
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 index = 3;</code>
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metapb.WorkflowWorker)
  }

  // @@protoc_insertion_point(class_scope:metapb.WorkflowWorker)
  private static final cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker();
  }

  public static cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkflowWorker>
      PARSER = new com.google.protobuf.AbstractParser<WorkflowWorker>() {
    public WorkflowWorker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkflowWorker(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkflowWorker> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkflowWorker> getParserForType() {
    return PARSER;
  }

  public cn.infinivision.dataforce.busybee.pb.meta.WorkflowWorker getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

