// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

package cn.infinivision.dataforce.busybee.pb.meta;

/**
 * <pre>
 * WorkflowInstanceState workflow instance state
 * </pre>
 *
 * Protobuf enum {@code metapb.WorkflowInstanceState}
 */
public enum WorkflowInstanceState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Starting = 0;</code>
   */
  Starting(0),
  /**
   * <code>Running = 1;</code>
   */
  Running(1),
  /**
   * <code>Stopping = 2;</code>
   */
  Stopping(2),
  /**
   * <code>Stopped = 3;</code>
   */
  Stopped(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Starting = 0;</code>
   */
  public static final int Starting_VALUE = 0;
  /**
   * <code>Running = 1;</code>
   */
  public static final int Running_VALUE = 1;
  /**
   * <code>Stopping = 2;</code>
   */
  public static final int Stopping_VALUE = 2;
  /**
   * <code>Stopped = 3;</code>
   */
  public static final int Stopped_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WorkflowInstanceState valueOf(int value) {
    return forNumber(value);
  }

  public static WorkflowInstanceState forNumber(int value) {
    switch (value) {
      case 0: return Starting;
      case 1: return Running;
      case 2: return Stopping;
      case 3: return Stopped;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WorkflowInstanceState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WorkflowInstanceState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WorkflowInstanceState>() {
          public WorkflowInstanceState findValueByNumber(int number) {
            return WorkflowInstanceState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cn.infinivision.dataforce.busybee.pb.meta.PB.getDescriptor().getEnumTypes().get(1);
  }

  private static final WorkflowInstanceState[] VALUES = values();

  public static WorkflowInstanceState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WorkflowInstanceState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:metapb.WorkflowInstanceState)
}

