// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.infinivision.dataforce.busybee.pb.api;

public final class PB {
  private PB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_KV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_KV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_Notify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_Notify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apipb_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apipb_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\005apipb\032\trpc.proto\"V\n\005Event\022\016" +
      "\n\006userID\030\001 \001(\r\022\020\n\010tenantID\030\002 \001(\004\022\022\n\nwork" +
      "flowID\030\003 \001(\004\022\027\n\004data\030\004 \003(\0132\t.apipb.KV\" \n" +
      "\002KV\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\"\225\001\n\006Noti" +
      "fy\022\016\n\006userID\030\001 \001(\r\022\r\n\005crowd\030\002 \001(\014\022\020\n\010ten" +
      "antID\030\003 \001(\004\022\022\n\nworkflowID\030\004 \001(\004\022\020\n\010fromS" +
      "tep\030\005 \001(\t\022\022\n\nfromAction\030\006 \001(\t\022\016\n\006toStep\030" +
      "\007 \001(\t\022\020\n\010toAction\030\010 \001(\t\"\331\007\n\007Request\022\n\n\002i" +
      "d\030\001 \001(\004\022\031\n\004type\030\002 \001(\0162\013.rpcpb.Type\022\036\n\003se" +
      "t\030\003 \001(\0132\021.rpcpb.SetRequest\022\036\n\003get\030\004 \001(\0132" +
      "\021.rpcpb.GetRequest\022$\n\006delete\030\005 \001(\0132\024.rpc" +
      "pb.DeleteRequest\022(\n\010bmCreate\030\006 \001(\0132\026.rpc" +
      "pb.BMCreateRequest\022\"\n\005bmAdd\030\007 \001(\0132\023.rpcp" +
      "b.BMAddRequest\022(\n\010bmRemove\030\010 \001(\0132\026.rpcpb" +
      ".BMRemoveRequest\022&\n\007bmClear\030\t \001(\0132\025.rpcp" +
      "b.BMClearRequest\022&\n\007bmRange\030\n \001(\0132\025.rpcp" +
      "b.BMRangeRequest\022&\n\007bmCount\030\013 \001(\0132\025.rpcp" +
      "b.BMCountRequest\022,\n\nbmContains\030\014 \001(\0132\030.r" +
      "pcpb.BMContainsRequest\022(\n\010queueAdd\030\r \001(\013" +
      "2\026.rpcpb.QueueAddRequest\022,\n\nqueueFetch\030\016" +
      " \001(\0132\030.rpcpb.QueueFetchRequest\022,\n\ntenant" +
      "Init\030\017 \001(\0132\030.rpcpb.TenantInitRequest\0225\n\r" +
      "startInstance\030\020 \001(\0132\036.rpcpb.StartingInst" +
      "anceRequest\0220\n\014stopInstance\030\021 \001(\0132\032.rpcp" +
      "b.StopInstanceRequest\0227\n\rcountInstance\030\022" +
      " \001(\0132 .rpcpb.InstanceCountStateRequest\0227" +
      "\n\rcrowdInstance\030\023 \001(\0132 .rpcpb.InstanceCr" +
      "owdStateRequest\0222\n\rupdateMapping\030\024 \001(\0132\033" +
      ".rpcpb.UpdateMappingRequest\022,\n\ngetMappin" +
      "g\030\025 \001(\0132\030.rpcpb.GetMappingRequest\0222\n\rupd" +
      "ateProfile\030\026 \001(\0132\033.rpcpb.UpdateProfileRe" +
      "quest\022,\n\ngetProfile\030\027 \001(\0132\030.rpcpb.GetPro" +
      "fileRequest\"\344\002\n\010Response\022\n\n\002id\030\001 \001(\004\022\031\n\004" +
      "type\030\002 \001(\0162\013.rpcpb.Type\022#\n\005error\030\003 \001(\0132\024" +
      ".apipb.ErrorResponse\022\'\n\tbytesResp\030\004 \001(\0132" +
      "\024.rpcpb.BytesResponse\022%\n\010boolResp\030\005 \001(\0132" +
      "\023.rpcpb.BoolResponse\022)\n\nuint64Resp\030\006 \001(\013" +
      "2\025.rpcpb.Uint64Response\0223\n\017uint32SliceRe" +
      "sp\030\007 \001(\0132\032.rpcpb.Uint32SliceResponse\0221\n\016" +
      "bytesSliceResp\030\010 \001(\0132\031.rpcpb.BytesSliceR" +
      "esponse\022)\n\nstringResp\030\t \001(\0132\025.rpcpb.Stri" +
      "ngResponse\"\036\n\rErrorResponse\022\r\n\005error\030\001 \001" +
      "(\tB6\n(cn.infinivision.dataforce.busybee." +
      "pb.apiB\002PBP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.infinivision.dataforce.busybee.pb.rpc.PB.getDescriptor(),
        }, assigner);
    internal_static_apipb_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apipb_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_Event_descriptor,
        new java.lang.String[] { "UserID", "TenantID", "WorkflowID", "Data", });
    internal_static_apipb_KV_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apipb_KV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_KV_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_apipb_Notify_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apipb_Notify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_Notify_descriptor,
        new java.lang.String[] { "UserID", "Crowd", "TenantID", "WorkflowID", "FromStep", "FromAction", "ToStep", "ToAction", });
    internal_static_apipb_Request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apipb_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_Request_descriptor,
        new java.lang.String[] { "Id", "Type", "Set", "Get", "Delete", "BmCreate", "BmAdd", "BmRemove", "BmClear", "BmRange", "BmCount", "BmContains", "QueueAdd", "QueueFetch", "TenantInit", "StartInstance", "StopInstance", "CountInstance", "CrowdInstance", "UpdateMapping", "GetMapping", "UpdateProfile", "GetProfile", });
    internal_static_apipb_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apipb_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_Response_descriptor,
        new java.lang.String[] { "Id", "Type", "Error", "BytesResp", "BoolResp", "Uint64Resp", "Uint32SliceResp", "BytesSliceResp", "StringResp", });
    internal_static_apipb_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apipb_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apipb_ErrorResponse_descriptor,
        new java.lang.String[] { "Error", });
    cn.infinivision.dataforce.busybee.pb.rpc.PB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
