// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface BytesSliceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.BytesSliceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes items = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getItemsList();
  /**
   * <code>repeated bytes items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated bytes items = 1;</code>
   */
  com.google.protobuf.ByteString getItems(int index);

  /**
   * <code>uint64 lastOffset = 2;</code>
   */
  long getLastOffset();
}
