// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface BytesSliceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.BytesSliceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes keys = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getKeysList();
  /**
   * <code>repeated bytes keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated bytes keys = 1;</code>
   */
  com.google.protobuf.ByteString getKeys(int index);

  /**
   * <code>repeated bytes values = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getValuesList();
  /**
   * <code>repeated bytes values = 2;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated bytes values = 2;</code>
   */
  com.google.protobuf.ByteString getValues(int index);

  /**
   * <code>uint64 lastValue = 3;</code>
   */
  long getLastValue();
}
