// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface InstanceCrowdStateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.InstanceCrowdStateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 workflowID = 1;</code>
   */
  long getWorkflowID();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
