// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public final class PB {
  private PB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_KV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_KV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Notify_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Notify_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_SetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_SetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMAddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMAddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMRemoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMRemoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMClearRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMClearRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMContainsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMContainsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BMRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BMRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_StartingInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_StartingInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateCrowdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateCrowdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateWorkflowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateWorkflowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_StartedInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_StartedInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_StopInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_StopInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_CreateInstanceStateShardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_CreateInstanceStateShardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateInstanceStateShardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateInstanceStateShardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_RemoveInstanceStateShardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_RemoveInstanceStateShardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_InstanceCountStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_InstanceCountStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_InstanceCrowdStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_InstanceCrowdStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_QueueAddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_QueueAddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_QueueFetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_QueueFetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TenantInitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TenantInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ScanMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ScanMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetIDSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetIDSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_UpdateProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_UpdateProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_AddEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_AddEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_FetchNotifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_FetchNotifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_AllocIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_AllocIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ResetIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ResetIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ScanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ScanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_EmptyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BytesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BytesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BoolResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BoolResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Uint64Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Uint64Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Uint32SliceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Uint32SliceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BytesSliceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BytesSliceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Uint32Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Uint32Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_Uint32RangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_Uint32RangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\005rpcpb\032\nmeta.proto\"V\n\005Event\022" +
      "\016\n\006userID\030\001 \001(\004\022\020\n\010tenantID\030\002 \001(\004\022\022\n\nwor" +
      "kflowID\030\003 \001(\004\022\027\n\004data\030\004 \003(\0132\t.rpcpb.KV\" " +
      "\n\002KV\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\"\225\001\n\006Not" +
      "ify\022\016\n\006userID\030\001 \001(\004\022\r\n\005crowd\030\002 \001(\014\022\020\n\010te" +
      "nantID\030\003 \001(\004\022\022\n\nworkflowID\030\004 \001(\004\022\020\n\010from" +
      "Step\030\005 \001(\t\022\022\n\nfromAction\030\006 \001(\t\022\016\n\006toStep" +
      "\030\007 \001(\t\022\020\n\010toAction\030\010 \001(\t\"\215\n\n\007Request\022\n\n\002" +
      "id\030\001 \001(\004\022\031\n\004type\030\002 \001(\0162\013.rpcpb.Type\022\036\n\003s" +
      "et\030\003 \001(\0132\021.rpcpb.SetRequest\022\036\n\003get\030\004 \001(\013" +
      "2\021.rpcpb.GetRequest\022$\n\006delete\030\005 \001(\0132\024.rp" +
      "cpb.DeleteRequest\022 \n\004scan\030\006 \001(\0132\022.rpcpb." +
      "ScanRequest\022(\n\010bmCreate\030\007 \001(\0132\026.rpcpb.BM" +
      "CreateRequest\022\"\n\005bmAdd\030\010 \001(\0132\023.rpcpb.BMA" +
      "ddRequest\022(\n\010bmRemove\030\t \001(\0132\026.rpcpb.BMRe" +
      "moveRequest\022&\n\007bmClear\030\n \001(\0132\025.rpcpb.BMC" +
      "learRequest\022&\n\007bmRange\030\013 \001(\0132\025.rpcpb.BMR" +
      "angeRequest\022&\n\007bmCount\030\014 \001(\0132\025.rpcpb.BMC" +
      "ountRequest\022,\n\nbmContains\030\r \001(\0132\030.rpcpb." +
      "BMContainsRequest\022,\n\ntenantInit\030\016 \001(\0132\030." +
      "rpcpb.TenantInitRequest\0225\n\rstartInstance" +
      "\030\017 \001(\0132\036.rpcpb.StartingInstanceRequest\022." +
      "\n\013updateCrowd\030\020 \001(\0132\031.rpcpb.UpdateCrowdR" +
      "equest\0224\n\016updateWorkflow\030\021 \001(\0132\034.rpcpb.U" +
      "pdateWorkflowRequest\0220\n\014stopInstance\030\022 \001" +
      "(\0132\032.rpcpb.StopInstanceRequest\0227\n\rcountI" +
      "nstance\030\023 \001(\0132 .rpcpb.InstanceCountState" +
      "Request\0227\n\rcrowdInstance\030\024 \001(\0132 .rpcpb.I" +
      "nstanceCrowdStateRequest\0222\n\rupdateMappin" +
      "g\030\025 \001(\0132\033.rpcpb.UpdateMappingRequest\022,\n\n" +
      "getMapping\030\026 \001(\0132\030.rpcpb.GetMappingReque" +
      "st\0222\n\rupdateProfile\030\027 \001(\0132\033.rpcpb.Update" +
      "ProfileRequest\022,\n\ngetProfile\030\030 \001(\0132\030.rpc" +
      "pb.GetProfileRequest\022(\n\010addEvent\030\031 \001(\0132\026" +
      ".rpcpb.AddEventRequest\022.\n\013fetchNotify\030\032 " +
      "\001(\0132\031.rpcpb.FetchNotifyRequest\022&\n\007allocI" +
      "D\030\033 \001(\0132\025.rpcpb.AllocIDRequest\022&\n\007resetI" +
      "D\030\034 \001(\0132\025.rpcpb.ResetIDRequest\022.\n\013scanMa" +
      "pping\030\035 \001(\0132\031.rpcpb.ScanMappingRequest\022(" +
      "\n\010getIDSet\030\036 \001(\0132\026.rpcpb.GetIDSetRequest" +
      "\"\304\003\n\010Response\022\n\n\002id\030\001 \001(\004\022\031\n\004type\030\002 \001(\0162" +
      "\013.rpcpb.Type\022#\n\005error\030\003 \001(\0132\024.rpcpb.Erro" +
      "rResponse\022\'\n\tbytesResp\030\004 \001(\0132\024.rpcpb.Byt" +
      "esResponse\022%\n\010boolResp\030\005 \001(\0132\023.rpcpb.Boo" +
      "lResponse\022)\n\nuint64Resp\030\006 \001(\0132\025.rpcpb.Ui" +
      "nt64Response\022)\n\nuint32Resp\030\007 \001(\0132\025.rpcpb" +
      ".Uint32Response\0223\n\017uint32RangeResp\030\010 \001(\013" +
      "2\032.rpcpb.Uint32RangeResponse\0223\n\017uint32Sl" +
      "iceResp\030\t \001(\0132\032.rpcpb.Uint32SliceRespons" +
      "e\0221\n\016bytesSliceResp\030\n \001(\0132\031.rpcpb.BytesS" +
      "liceResponse\022)\n\nstringResp\030\013 \001(\0132\025.rpcpb" +
      ".StringResponse\"(\n\nSetRequest\022\013\n\003key\030\001 \001" +
      "(\014\022\r\n\005value\030\002 \001(\014\"\031\n\nGetRequest\022\013\n\003key\030\001" +
      " \001(\014\"\034\n\rDeleteRequest\022\013\n\003key\030\001 \001(\014\"-\n\017BM" +
      "CreateRequest\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \003(" +
      "\004\"*\n\014BMAddRequest\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030" +
      "\002 \003(\004\"-\n\017BMRemoveRequest\022\013\n\003key\030\001 \001(\014\022\r\n" +
      "\005value\030\002 \003(\004\"\035\n\016BMClearRequest\022\013\n\003key\030\001 " +
      "\001(\014\"/\n\021BMContainsRequest\022\013\n\003key\030\001 \001(\014\022\r\n" +
      "\005value\030\002 \003(\004\"\035\n\016BMCountRequest\022\013\n\003key\030\001 " +
      "\001(\014\";\n\016BMRangeRequest\022\013\n\003key\030\001 \001(\014\022\r\n\005st" +
      "art\030\002 \001(\004\022\r\n\005limit\030\003 \001(\004\"E\n\027StartingInst" +
      "anceRequest\022*\n\010instance\030\001 \001(\0132\030.metapb.W" +
      "orkflowInstance\"C\n\025UpdateInstanceRequest" +
      "\022*\n\010instance\030\001 \001(\0132\030.metapb.WorkflowInst" +
      "ance\"/\n\022UpdateCrowdRequest\022\n\n\002id\030\001 \001(\004\022\r" +
      "\n\005crowd\030\002 \001(\014\";\n\025UpdateWorkflowRequest\022\"" +
      "\n\010workflow\030\001 \001(\0132\020.metapb.Workflow\",\n\026St" +
      "artedInstanceRequest\022\022\n\nworkflowID\030\001 \001(\004" +
      "\")\n\023StopInstanceRequest\022\022\n\nworkflowID\030\001 " +
      "\001(\004\"O\n\037CreateInstanceStateShardRequest\022," +
      "\n\005state\030\001 \001(\0132\035.metapb.WorkflowInstanceS" +
      "tate\"O\n\037UpdateInstanceStateShardRequest\022" +
      ",\n\005state\030\001 \001(\0132\035.metapb.WorkflowInstance" +
      "State\"D\n\037RemoveInstanceStateShardRequest" +
      "\022\022\n\nworkflowID\030\001 \001(\004\022\r\n\005index\030\002 \001(\r\"/\n\031I" +
      "nstanceCountStateRequest\022\022\n\nworkflowID\030\001" +
      " \001(\004\"=\n\031InstanceCrowdStateRequest\022\022\n\nwor" +
      "kflowID\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\"-\n\017QueueAddR" +
      "equest\022\013\n\003key\030\001 \001(\014\022\r\n\005items\030\002 \003(\014\"o\n\021Qu" +
      "eueFetchRequest\022\013\n\003key\030\001 \001(\014\022\020\n\010consumer" +
      "\030\002 \001(\014\022\027\n\017completedOffset\030\003 \001(\004\022\r\n\005count" +
      "\030\004 \001(\004\022\023\n\013concurrency\030\005 \001(\004\"=\n\021TenantIni" +
      "tRequest\022\n\n\002id\030\001 \001(\004\022\034\n\024inputQueuePartit" +
      "ions\030\002 \001(\004\"I\n\022ScanMappingRequest\022\n\n\002id\030\001" +
      " \001(\004\022\014\n\004from\030\002 \001(\004\022\n\n\002to\030\003 \001(\004\022\r\n\005limit\030" +
      "\004 \001(\004\"-\n\017GetIDSetRequest\022\n\n\002id\030\001 \001(\004\022\016\n\006" +
      "userID\030\002 \001(\004\"N\n\024UpdateMappingRequest\022\n\n\002" +
      "id\030\001 \001(\004\022\016\n\006userID\030\002 \001(\004\022\032\n\003set\030\003 \001(\0132\r." +
      "metapb.IDSet\"J\n\021GetMappingRequest\022\n\n\002id\030" +
      "\001 \001(\004\022\035\n\004from\030\002 \001(\0132\017.metapb.IDValue\022\n\n\002" +
      "to\030\003 \001(\t\"A\n\024UpdateProfileRequest\022\n\n\002id\030\001" +
      " \001(\004\022\016\n\006userID\030\002 \001(\004\022\r\n\005value\030\003 \001(\014\">\n\021G" +
      "etProfileRequest\022\n\n\002id\030\001 \001(\004\022\016\n\006userID\030\002" +
      " \001(\004\022\r\n\005field\030\003 \001(\t\"3\n\017AddEventRequest\022 " +
      "\n\005event\030\001 \001(\0132\021.metapb.UserEvent\"o\n\022Fetc" +
      "hNotifyRequest\022\n\n\002id\030\001 \001(\004\022\027\n\017completedO" +
      "ffset\030\002 \001(\004\022\r\n\005count\030\003 \001(\004\022\020\n\010consumer\030\004" +
      " \001(\t\022\023\n\013concurrency\030\005 \001(\004\",\n\016AllocIDRequ" +
      "est\022\013\n\003key\030\001 \001(\014\022\r\n\005batch\030\002 \001(\004\"0\n\016Reset" +
      "IDRequest\022\013\n\003key\030\001 \001(\014\022\021\n\tstartWith\030\002 \001(" +
      "\004\"d\n\013ScanRequest\022\r\n\005start\030\001 \001(\014\022\013\n\003end\030\002" +
      " \001(\014\022\r\n\005limit\030\003 \001(\004\022\014\n\004skip\030\004 \001(\005\022\034\n\005gro" +
      "up\030\005 \001(\0162\r.metapb.Group\"\036\n\rErrorResponse" +
      "\022\r\n\005error\030\001 \001(\t\"\017\n\rEmptyResponse\"\037\n\016Stri" +
      "ngResponse\022\r\n\005value\030\001 \001(\t\"\036\n\rBytesRespon" +
      "se\022\r\n\005value\030\001 \001(\014\"\035\n\014BoolResponse\022\r\n\005val" +
      "ue\030\001 \001(\010\"\037\n\016Uint64Response\022\r\n\005value\030\001 \001(" +
      "\004\"%\n\023Uint32SliceResponse\022\016\n\006values\030\001 \003(\004" +
      "\"7\n\022BytesSliceResponse\022\r\n\005items\030\001 \003(\014\022\022\n" +
      "\nlastOffset\030\002 \001(\004\"\037\n\016Uint32Response\022\r\n\005v" +
      "alue\030\001 \001(\004\"/\n\023Uint32RangeResponse\022\014\n\004fro" +
      "m\030\001 \001(\004\022\n\n\002to\030\002 \001(\004*\360\004\n\004Type\022\007\n\003Set\020\000\022\007\n" +
      "\003Get\020\001\022\n\n\006Delete\020\002\022\010\n\004Scan\020\003\022\014\n\010BMCreate" +
      "\020d\022\t\n\005BMAdd\020e\022\014\n\010BMRemove\020f\022\013\n\007BMClear\020g" +
      "\022\016\n\nBMContains\020h\022\013\n\007BMCount\020i\022\013\n\007BMRange" +
      "\020j\022\025\n\020StartingInstance\020\310\001\022\023\n\016UpdateWorkf" +
      "low\020\311\001\022\020\n\013UpdateCrowd\020\312\001\022\023\n\016UpdateInstan" +
      "ce\020\313\001\022\024\n\017StartedInstance\020\314\001\022\021\n\014StopInsta" +
      "nce\020\315\001\022\035\n\030CreateInstanceStateShard\020\316\001\022\035\n" +
      "\030UpdateInstanceStateShard\020\317\001\022\035\n\030RemoveIn" +
      "stanceStateShard\020\320\001\022\027\n\022InstanceCountStat" +
      "e\020\321\001\022\027\n\022InstanceCrowdState\020\322\001\022\r\n\010QueueAd" +
      "d\020\254\002\022\017\n\nQueueFetch\020\255\002\022\017\n\nTenantInit\020\220\003\022\022" +
      "\n\rUpdateMapping\020\221\003\022\017\n\nGetMapping\020\222\003\022\022\n\rU" +
      "pdateProfile\020\223\003\022\017\n\nGetProfile\020\224\003\022\r\n\010AddE" +
      "vent\020\225\003\022\020\n\013FetchNotify\020\226\003\022\020\n\013ScanMapping" +
      "\020\227\003\022\r\n\010GetIDSet\020\230\003\022\014\n\007AllocID\020\365\003\022\014\n\007Rese" +
      "tID\020\366\003B6\n(cn.infinivision.dataforce.busy" +
      "bee.pb.rpcB\002PBP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.infinivision.dataforce.busybee.pb.meta.PB.getDescriptor(),
        }, assigner);
    internal_static_rpcpb_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpcpb_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Event_descriptor,
        new java.lang.String[] { "UserID", "TenantID", "WorkflowID", "Data", });
    internal_static_rpcpb_KV_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpcpb_KV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_KV_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_Notify_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpcpb_Notify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Notify_descriptor,
        new java.lang.String[] { "UserID", "Crowd", "TenantID", "WorkflowID", "FromStep", "FromAction", "ToStep", "ToAction", });
    internal_static_rpcpb_Request_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpcpb_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Request_descriptor,
        new java.lang.String[] { "Id", "Type", "Set", "Get", "Delete", "Scan", "BmCreate", "BmAdd", "BmRemove", "BmClear", "BmRange", "BmCount", "BmContains", "TenantInit", "StartInstance", "UpdateCrowd", "UpdateWorkflow", "StopInstance", "CountInstance", "CrowdInstance", "UpdateMapping", "GetMapping", "UpdateProfile", "GetProfile", "AddEvent", "FetchNotify", "AllocID", "ResetID", "ScanMapping", "GetIDSet", });
    internal_static_rpcpb_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpcpb_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Response_descriptor,
        new java.lang.String[] { "Id", "Type", "Error", "BytesResp", "BoolResp", "Uint64Resp", "Uint32Resp", "Uint32RangeResp", "Uint32SliceResp", "BytesSliceResp", "StringResp", });
    internal_static_rpcpb_SetRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpcpb_SetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_SetRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpcpb_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_rpcpb_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpcpb_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_DeleteRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_rpcpb_BMCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpcpb_BMCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMCreateRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_BMAddRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpcpb_BMAddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMAddRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_BMRemoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpcpb_BMRemoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMRemoveRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_BMClearRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpcpb_BMClearRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMClearRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_rpcpb_BMContainsRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rpcpb_BMContainsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMContainsRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpcpb_BMCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rpcpb_BMCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMCountRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_rpcpb_BMRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rpcpb_BMRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BMRangeRequest_descriptor,
        new java.lang.String[] { "Key", "Start", "Limit", });
    internal_static_rpcpb_StartingInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_rpcpb_StartingInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_StartingInstanceRequest_descriptor,
        new java.lang.String[] { "Instance", });
    internal_static_rpcpb_UpdateInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_rpcpb_UpdateInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateInstanceRequest_descriptor,
        new java.lang.String[] { "Instance", });
    internal_static_rpcpb_UpdateCrowdRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_rpcpb_UpdateCrowdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateCrowdRequest_descriptor,
        new java.lang.String[] { "Id", "Crowd", });
    internal_static_rpcpb_UpdateWorkflowRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_rpcpb_UpdateWorkflowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateWorkflowRequest_descriptor,
        new java.lang.String[] { "Workflow", });
    internal_static_rpcpb_StartedInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_rpcpb_StartedInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_StartedInstanceRequest_descriptor,
        new java.lang.String[] { "WorkflowID", });
    internal_static_rpcpb_StopInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_rpcpb_StopInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_StopInstanceRequest_descriptor,
        new java.lang.String[] { "WorkflowID", });
    internal_static_rpcpb_CreateInstanceStateShardRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_rpcpb_CreateInstanceStateShardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_CreateInstanceStateShardRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpcpb_UpdateInstanceStateShardRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_rpcpb_UpdateInstanceStateShardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateInstanceStateShardRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpcpb_RemoveInstanceStateShardRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_rpcpb_RemoveInstanceStateShardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_RemoveInstanceStateShardRequest_descriptor,
        new java.lang.String[] { "WorkflowID", "Index", });
    internal_static_rpcpb_InstanceCountStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_rpcpb_InstanceCountStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_InstanceCountStateRequest_descriptor,
        new java.lang.String[] { "WorkflowID", });
    internal_static_rpcpb_InstanceCrowdStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_rpcpb_InstanceCrowdStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_InstanceCrowdStateRequest_descriptor,
        new java.lang.String[] { "WorkflowID", "Name", });
    internal_static_rpcpb_QueueAddRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_rpcpb_QueueAddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_QueueAddRequest_descriptor,
        new java.lang.String[] { "Key", "Items", });
    internal_static_rpcpb_QueueFetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_rpcpb_QueueFetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_QueueFetchRequest_descriptor,
        new java.lang.String[] { "Key", "Consumer", "CompletedOffset", "Count", "Concurrency", });
    internal_static_rpcpb_TenantInitRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_rpcpb_TenantInitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TenantInitRequest_descriptor,
        new java.lang.String[] { "Id", "InputQueuePartitions", });
    internal_static_rpcpb_ScanMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_rpcpb_ScanMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ScanMappingRequest_descriptor,
        new java.lang.String[] { "Id", "From", "To", "Limit", });
    internal_static_rpcpb_GetIDSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_rpcpb_GetIDSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetIDSetRequest_descriptor,
        new java.lang.String[] { "Id", "UserID", });
    internal_static_rpcpb_UpdateMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_rpcpb_UpdateMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateMappingRequest_descriptor,
        new java.lang.String[] { "Id", "UserID", "Set", });
    internal_static_rpcpb_GetMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_rpcpb_GetMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetMappingRequest_descriptor,
        new java.lang.String[] { "Id", "From", "To", });
    internal_static_rpcpb_UpdateProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_rpcpb_UpdateProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_UpdateProfileRequest_descriptor,
        new java.lang.String[] { "Id", "UserID", "Value", });
    internal_static_rpcpb_GetProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_rpcpb_GetProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetProfileRequest_descriptor,
        new java.lang.String[] { "Id", "UserID", "Field", });
    internal_static_rpcpb_AddEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_rpcpb_AddEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_AddEventRequest_descriptor,
        new java.lang.String[] { "Event", });
    internal_static_rpcpb_FetchNotifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_rpcpb_FetchNotifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_FetchNotifyRequest_descriptor,
        new java.lang.String[] { "Id", "CompletedOffset", "Count", "Consumer", "Concurrency", });
    internal_static_rpcpb_AllocIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_rpcpb_AllocIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_AllocIDRequest_descriptor,
        new java.lang.String[] { "Key", "Batch", });
    internal_static_rpcpb_ResetIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_rpcpb_ResetIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ResetIDRequest_descriptor,
        new java.lang.String[] { "Key", "StartWith", });
    internal_static_rpcpb_ScanRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_rpcpb_ScanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ScanRequest_descriptor,
        new java.lang.String[] { "Start", "End", "Limit", "Skip", "Group", });
    internal_static_rpcpb_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_rpcpb_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ErrorResponse_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_rpcpb_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_rpcpb_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_EmptyResponse_descriptor,
        new java.lang.String[] { });
    internal_static_rpcpb_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_rpcpb_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_StringResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpcpb_BytesResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_rpcpb_BytesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BytesResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpcpb_BoolResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_rpcpb_BoolResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BoolResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpcpb_Uint64Response_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_rpcpb_Uint64Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Uint64Response_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpcpb_Uint32SliceResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_rpcpb_Uint32SliceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Uint32SliceResponse_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_rpcpb_BytesSliceResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_rpcpb_BytesSliceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BytesSliceResponse_descriptor,
        new java.lang.String[] { "Items", "LastOffset", });
    internal_static_rpcpb_Uint32Response_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_rpcpb_Uint32Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Uint32Response_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_rpcpb_Uint32RangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_rpcpb_Uint32RangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_Uint32RangeResponse_descriptor,
        new java.lang.String[] { "From", "To", });
    cn.infinivision.dataforce.busybee.pb.meta.PB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
