// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface QueueDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.QueueDeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>uint64 id = 2;</code>
   */
  long getId();

  /**
   * <code>uint32 partition = 3;</code>
   */
  int getPartition();

  /**
   * <code>uint64 from = 4;</code>
   */
  long getFrom();

  /**
   * <code>uint64 to = 5;</code>
   */
  long getTo();
}
