// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

/**
 * <pre>
 * QueueAddRequest add items into a queue
 * </pre>
 *
 * Protobuf type {@code rpcpb.QueueAddRequest}
 */
public  final class QueueAddRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpcpb.QueueAddRequest)
    QueueAddRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueueAddRequest.newBuilder() to construct.
  private QueueAddRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueueAddRequest() {
    key_ = com.google.protobuf.ByteString.EMPTY;
    items_ = java.util.Collections.emptyList();
    kvs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueueAddRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            key_ = input.readBytes();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              items_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000002;
            }
            items_.add(input.readBytes());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              kvs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000004;
            }
            kvs_.add(input.readBytes());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        kvs_ = java.util.Collections.unmodifiableList(kvs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.infinivision.dataforce.busybee.pb.rpc.PB.internal_static_rpcpb_QueueAddRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.infinivision.dataforce.busybee.pb.rpc.PB.internal_static_rpcpb_QueueAddRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.class, cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.Builder.class);
  }

  private int bitField0_;
  public static final int KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString key_;
  /**
   * <code>bytes key = 1;</code>
   */
  public com.google.protobuf.ByteString getKey() {
    return key_;
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  private java.util.List<com.google.protobuf.ByteString> items_;
  /**
   * <code>repeated bytes items = 2;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getItemsList() {
    return items_;
  }
  /**
   * <code>repeated bytes items = 2;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated bytes items = 2;</code>
   */
  public com.google.protobuf.ByteString getItems(int index) {
    return items_.get(index);
  }

  public static final int KVS_FIELD_NUMBER = 3;
  private java.util.List<com.google.protobuf.ByteString> kvs_;
  /**
   * <code>repeated bytes kvs = 3;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getKvsList() {
    return kvs_;
  }
  /**
   * <code>repeated bytes kvs = 3;</code>
   */
  public int getKvsCount() {
    return kvs_.size();
  }
  /**
   * <code>repeated bytes kvs = 3;</code>
   */
  public com.google.protobuf.ByteString getKvs(int index) {
    return kvs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!key_.isEmpty()) {
      output.writeBytes(1, key_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeBytes(2, items_.get(i));
    }
    for (int i = 0; i < kvs_.size(); i++) {
      output.writeBytes(3, kvs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!key_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, key_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < items_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(items_.get(i));
      }
      size += dataSize;
      size += 1 * getItemsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < kvs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(kvs_.get(i));
      }
      size += dataSize;
      size += 1 * getKvsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest)) {
      return super.equals(obj);
    }
    cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest other = (cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest) obj;

    boolean result = true;
    result = result && getKey()
        .equals(other.getKey());
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && getKvsList()
        .equals(other.getKvsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (getKvsCount() > 0) {
      hash = (37 * hash) + KVS_FIELD_NUMBER;
      hash = (53 * hash) + getKvsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * QueueAddRequest add items into a queue
   * </pre>
   *
   * Protobuf type {@code rpcpb.QueueAddRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpcpb.QueueAddRequest)
      cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.infinivision.dataforce.busybee.pb.rpc.PB.internal_static_rpcpb_QueueAddRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.infinivision.dataforce.busybee.pb.rpc.PB.internal_static_rpcpb_QueueAddRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.class, cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.Builder.class);
    }

    // Construct using cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      key_ = com.google.protobuf.ByteString.EMPTY;

      items_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      kvs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.infinivision.dataforce.busybee.pb.rpc.PB.internal_static_rpcpb_QueueAddRequest_descriptor;
    }

    public cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest getDefaultInstanceForType() {
      return cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.getDefaultInstance();
    }

    public cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest build() {
      cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest buildPartial() {
      cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest result = new cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.key_ = key_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        items_ = java.util.Collections.unmodifiableList(items_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.items_ = items_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        kvs_ = java.util.Collections.unmodifiableList(kvs_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.kvs_ = kvs_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest) {
        return mergeFrom((cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest other) {
      if (other == cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest.getDefaultInstance()) return this;
      if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
        setKey(other.getKey());
      }
      if (!other.items_.isEmpty()) {
        if (items_.isEmpty()) {
          items_ = other.items_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureItemsIsMutable();
          items_.addAll(other.items_);
        }
        onChanged();
      }
      if (!other.kvs_.isEmpty()) {
        if (kvs_.isEmpty()) {
          kvs_ = other.kvs_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureKvsIsMutable();
          kvs_.addAll(other.kvs_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes key = 1;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }
    /**
     * <code>bytes key = 1;</code>
     */
    public Builder setKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes key = 1;</code>
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> items_ = java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        items_ = new java.util.ArrayList<com.google.protobuf.ByteString>(items_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getItemsList() {
      return java.util.Collections.unmodifiableList(items_);
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public com.google.protobuf.ByteString getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public Builder setItems(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureItemsIsMutable();
      items_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public Builder addItems(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureItemsIsMutable();
      items_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureItemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, items_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes items = 2;</code>
     */
    public Builder clearItems() {
      items_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> kvs_ = java.util.Collections.emptyList();
    private void ensureKvsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        kvs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(kvs_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getKvsList() {
      return java.util.Collections.unmodifiableList(kvs_);
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public int getKvsCount() {
      return kvs_.size();
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public com.google.protobuf.ByteString getKvs(int index) {
      return kvs_.get(index);
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public Builder setKvs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKvsIsMutable();
      kvs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public Builder addKvs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKvsIsMutable();
      kvs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public Builder addAllKvs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureKvsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, kvs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes kvs = 3;</code>
     */
    public Builder clearKvs() {
      kvs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpcpb.QueueAddRequest)
  }

  // @@protoc_insertion_point(class_scope:rpcpb.QueueAddRequest)
  private static final cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest();
  }

  public static cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueueAddRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueueAddRequest>() {
    public QueueAddRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueueAddRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueueAddRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueueAddRequest> getParserForType() {
    return PARSER;
  }

  public cn.infinivision.dataforce.busybee.pb.rpc.QueueAddRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

