// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface RemoveInstanceStateShardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.RemoveInstanceStateShardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 workflowID = 1;</code>
   */
  long getWorkflowID();

  /**
   * <code>uint32 start = 2;</code>
   */
  int getStart();

  /**
   * <code>uint32 end = 3;</code>
   */
  int getEnd();
}
