// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface ResetIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.ResetIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>uint64 startWith = 2;</code>
   */
  long getStartWith();
}
