// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface ScanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.ScanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes start = 1;</code>
   */
  com.google.protobuf.ByteString getStart();

  /**
   * <code>bytes end = 2;</code>
   */
  com.google.protobuf.ByteString getEnd();

  /**
   * <code>uint64 limit = 3;</code>
   */
  long getLimit();

  /**
   * <code>.metapb.Group group = 4;</code>
   */
  int getGroupValue();
  /**
   * <code>.metapb.Group group = 4;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.Group getGroup();
}
