// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface Uint32RangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.Uint32RangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 from = 1;</code>
   */
  long getFrom();

  /**
   * <code>uint64 to = 2;</code>
   */
  long getTo();
}
