// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface UpdateMappingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.UpdateMappingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>uint64 userID = 2;</code>
   */
  long getUserID();

  /**
   * <code>.metapb.IDSet set = 3;</code>
   */
  boolean hasSet();
  /**
   * <code>.metapb.IDSet set = 3;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.IDSet getSet();
  /**
   * <code>.metapb.IDSet set = 3;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.IDSetOrBuilder getSetOrBuilder();
}
