// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface UpdateInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.UpdateInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.metapb.WorkflowInstance instance = 1;</code>
   */
  boolean hasInstance();
  /**
   * <code>.metapb.WorkflowInstance instance = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.WorkflowInstance getInstance();
  /**
   * <code>.metapb.WorkflowInstance instance = 1;</code>
   */
  cn.infinivision.dataforce.busybee.pb.meta.WorkflowInstanceOrBuilder getInstanceOrBuilder();
}
