// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface UpdateCrowdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.UpdateCrowdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>bytes crowd = 2;</code>
   */
  com.google.protobuf.ByteString getCrowd();
}
