// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.infinivision.dataforce.busybee.pb.rpc;

public interface UpdateProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.UpdateProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>uint32 userID = 2;</code>
   */
  int getUserID();

  /**
   * <code>bytes value = 3;</code>
   */
  com.google.protobuf.ByteString getValue();
}
